version: "3"
services:
  jenkins:
    build: build/
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - "jenkins.data:/var/jenkins_home"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/usr/bin/docker:/usr/bin/docker"
    - "/home/mehedi/.kube:/.kube"

volumes:
  jenkins.data:

networks:
  default:
    external:
      name: minikube